BLOB_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=aljazeerastore;AccountKey=RElwkKk79TmuitT8kSYXJsfUGMYLV3jpe90Jd5rrps42AL8jpxX6YRM2c6VQNlmwt7FTBC8nUWkA+ASteMWjgQ==;EndpointSuffix=core.windows.net"
BLOB_CONTAINER_NAME = "chatbotrawlayer"
BLOB_FILE_NAME = "aljazeera_articles.csv"
OPENAI_ENDPOINT="https://aljazeerapoc.openai.azure.com/"
OPENAI_API_KEY="1Jwu9eGv8O33NfLDzXsy8oWuaM7PTd9YxR5fsE3yHWuRke2POqlGJQQJ99BEACYeBjFXJ3w3AAABACOGtoar"
OPENAI_API_VERSION = "2024-12-01-preview"
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-aljazeera"
OPENAI_TYPE = "azure"
CHAT_DEPLOYMENT_NAME = "gpt-4o-aljazeera"